# Site settings
name: Jesus Rincon
title: Jesus Rincon | Software Engineer
description: Software engineer focused on the web, the cloud (AWS) and mobile (iOS)
url: https://chuckrincon.github.io/
baseurl: ''
email: chuckrincon@gmail.com
cover: https://chuckrincon.github.io/img/og.png
logo: https://chuckrincon.github.io/img/emojis/technologist.png
resume: https://chuckrincon.github.io/Resume - Jesus Rincon - Software engineer.pdf
social:
  - title: email
    url: mailto:chuckrincon@gmail.com
  - title: twitter
    url: https://twitter.com/chuckrincon
  - title: instagram
    url: https://instagram.com/chuck.rincon
  - title: github
    url: https://github.com/chuckrincon
  - title: linkedin
    url: https://www.linkedin.com/in/jesus-rincon

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
